name: Maven Tests

# Trigger the workflow on push or pull request events to the main branch
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

# Define the jobs that the workflow will run
jobs:
  test:
    # Runs the job on a virtual machine with Ubuntu installed
    runs-on: ubuntu-latest

    # Steps to execute within the job
    steps:
      # Step 1: Check out the repository to the virtual machine
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up the required Java version
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run the Maven tests and generate a coverage report
      - name: Run tests and generate coverage report
        run: mvn clean verify jacoco:report

      # Step 5: Make the coverage report downloadable
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco